# Colorado model
## Current situation - simulation script

In [73]:
include("../src/nui.jl")

┌──────────────────────────────────────────────────┐
│    ▄▄    ▄▄      ▄▄    ▄▄       ▄▄▄▄    ▄▄    ▄▄ │
│   ████   ██      ██   ████    ▄█▀▀▀▀█   ██    ██ │
│   ████   ▀█▄ ██ ▄█▀   ████    ██▄       ██    ██ │
│  ██  ██   ██ ██ ██   ██  ██    ▀████▄   ████████ │
│  ██████   ███▀▀███   ██████        ▀██  ██    ██ │
│ ▄██  ██▄  ███  ███  ▄██  ██▄  █▄▄▄▄▄█▀  ██    ██ │
│ ▀▀    ▀▀  ▀▀▀  ▀▀▀  ▀▀    ▀▀   ▀▀▀▀▀    ▀▀    ▀▀ │
└──────────────────────────────────────────────────┘

Welcome to AWASH, the America's Water Model, version 0.7.



In [136]:
include("../src/simulate_colorado.jl")

Loading from saved region network...
Loading from saved water network...
Loading from saved region network...


Creating model...


Running model for Colorado state ...
  0.855808 seconds (563.87 k allocations: 18.370 MB, 2.39% gc time)


3109x12 Array{Float64,2}:
  NaN      NaN      NaN      NaN     …   NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN     …   NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN     …   NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   

In [141]:
agriculture = initagriculture(model);
m= model;

In [142]:
logirrigatedyield = -Inf * ones(numcounties, numcrops, numsteps)
    deficit_coeff = zeros(numcounties, numcrops)
    for cc in 1:numcrops
        # Load degree day data
        gdds = readtable(joinpath(todata, "agriculture/edds/$(crops[cc])-gdd.csv"))
        kdds = readtable(joinpath(todata, "agriculture/edds/$(crops[cc])-kdd.csv"))

        for rr in 1:numcounties
            fips = parse(Int64, mastercounties[rr, :fips])
            if fips in keys(agmodels[crops[cc]])
                thismodel = agmodels[crops[cc]][fips]
                for tt in 1:numsteps
                    year = index2year(tt)
                    if year >= 1949 && year <= 2009
                        numgdds = gdds[rr, symbol("x$year")]
                        if isna(numgdds)
                            numgdds = 0
                        end

                        numkdds = kdds[rr, symbol("x$year")]
                        if isna(numkdds)
                            numkdds = 0
                        end
                    else
                        numgdds = numkdds = 0
                    end

                    logmodelyield = thismodel.intercept + thismodel.gdds * numgdds + thismodel.kdds * numkdds
                    logirrigatedyield[rr, cc, tt] = min(logmodelyield, log(maximum_yields[crops[cc]]))
                end

                deficit_coeff[rr, cc] = min(0., thismodel.wreq) # must be negative
            end
        end
    end

    water_demand = zeros(numcrops)
    for cc in 1:numcrops
        water_demand[cc] = water_requirements[crops[cc]] * 1000
    end


3109x12 Array{Float64,2}:
  NaN      NaN      NaN      NaN     …   NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN     …   NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN     …   NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   
  NaN      NaN      NaN      NaN         NaN      NaN      NaN      NaN   

In [145]:
logirrigatedyield = -Inf * ones(numcounties, numcrops, numsteps)
    deficit_coeff = zeros(numcounties, numcrops)
    for cc in 1:numcrops
        # Load degree day data
        gdds = readtable(joinpath(todata, "agriculture/edds/$(crops[cc])-gdd.csv"))
        kdds = readtable(joinpath(todata, "agriculture/edds/$(crops[cc])-kdd.csv"))

        for rr in 1:numcounties
            fips = parse(Int64, mastercounties[rr, :fips])
            if fips in keys(agmodels[crops[cc]])
                thismodel = agmodels[crops[cc]][fips]
                for tt in 1:numsteps
                    year = index2year(tt)
                    if year >= 1949 && year <= 2009
                        numgdds = gdds[rr, symbol("x$year")]
                        if isna(numgdds)
                            numgdds = 0
                        end

                        numkdds = kdds[rr, symbol("x$year")]
                        if isna(numkdds)
                            numkdds = 0
                        end
                    else
                        numgdds = numkdds = 0
                    end

                    logmodelyield = thismodel.intercept + thismodel.gdds * numgdds + thismodel.kdds * numkdds
                    logirrigatedyield[rr, cc, tt] = min(logmodelyield, log(maximum_yields[crops[cc]]))
                end

                deficit_coeff[rr, cc] = min(0., thismodel.wreq) # must be negative
            end
        end
    end
water_demand = zeros(numcrops)
    for cc in 1:numcrops
        water_demand[cc] = water_requirements[crops[cc]] * 1000
    end


In [148]:
    agriculture = addcomponent(m, Agriculture)

    agriculture[:logirrigatedyield] = logirrigatedyield
    agriculture[:deficit_coeff] = deficit_coeff
    agriculture[:water_demand] = water_demand
    agriculture[:precipitation] = precip;

In [152]:
# Load in planted area by water management
    rainfeds = readtable(joinpath(todata, "agriculture/rainfedareas.csv"))
    irrigateds = readtable(joinpath(todata, "agriculture/irrigatedareas.csv"))
    for cc in 2:ncol(rainfeds)
        # Replace NAs with 0, and convert to float. TODO: improve this
        rainfeds[isna(rainfeds[cc]), cc] = 0.
        irrigateds[isna(irrigateds[cc]), cc] = 0.
        # Convert to Ha
        rainfeds[cc] = rainfeds[cc] * 0.404686
        irrigateds[cc] = irrigateds[cc] * 0.404686
    end
    agriculture[:rainfedareas] = repeat(convert(Matrix, rainfeds[:, 2:end]), outer=[1, 1, numsteps])
    agriculture[:irrigatedareas] = repeat(convert(Matrix, irrigateds[:, 2:end]), outer=[1, 1, numsteps])


3109x9x12 Array{Float64,3}:
[:, :, 1] =
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       2.42812     0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     0.0       0.0         0.0     0.0     0.0    0.0  0.0    0.0    0.0
     ⋮     

In [153]:
knownareas = readtable(datapath("agriculture/knownareas.csv"))
    agriculture[:othercropsarea] = repeat(convert(Vector, knownareas[:total] - knownareas[:known]), outer=[1, numsteps])

3109x12 Array{Float64,2}:
     0.0      0.0      0.0      0.0  …      0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0  …      0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0  …      0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0

In [155]:
recorded = readtable(datapath("extraction/USGS-2010.csv"));

In [159]:
agriculture[:othercropsirrigation] = repeat(convert(Vector, ((knownareas[:total] - knownareas[:known]) ./ knownareas[:total])), outer=[1, numsteps])


3109x12 Array{Float64,2}:
 NaN          NaN          NaN          …  NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN          …  NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN          …  NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
 NaN          NaN          NaN             NaN          NaN        
   ⋮                                    ⋱    ⋮                     
   0.0          0.0   

In [160]:
knownareas[:total]

3109-element DataArrays.DataArray{Float64,1}:
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     ⋮  
 82800.0
 30500.0
 32000.0
 81600.0
 43900.0
 68300.0
 78800.0
 24900.0
  6500.0
 48200.0
 35900.0
 32500.0

In [135]:
knownareas = readtable(datapath("agriculture/knownareas.csv"))
    recorded = readtable(datapath("extraction/USGS-2010.csv"))
    agriculture[:othercropsarea] = repeat(convert(Vector, knownareas[:total] - knownareas[:known]), outer=[1, numsteps])

3109x12 Array{Float64,2}:
     0.0      0.0      0.0      0.0  …      0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0  …      0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0  …      0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0
     0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0

In [133]:
repeat(convert(Vector, ((knownareas[:total] - knownareas[:known]) ./ knownareas[:total]) * config["timestep"] .* recorded[:, :IR_To] * 1382592. / (1000. * 12)), outer=[1, numsteps])

LoadError: LoadError: KeyError: IR_To not found
while loading In[133], in expression starting on line 1

In [82]:
getdata(:Thermoelectric, :demand_copy)

63x12 Array{Float64,2}:
 67.7524  58.5391  63.8796  58.6938  …  67.4809  65.7446  62.1734  69.0714
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0     …   0.0      0.0      0.0      0.0   
 39.6695  34.2751  37.402   34.3656     39.5106  38.494   36.403   40.4418
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0     …   0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
 

In [83]:
model.components[:Thermoelectric].Parameters.demand

64x12 Array{Float64,2}:
 67.7524  58.5391  63.8796  58.6938  …  67.4809  65.7446  62.1734  69.0714
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0     …   0.0      0.0      0.0      0.0   
 39.6695  34.2751  37.402   34.3656     39.5106  38.494   36.403   40.4418
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0     …   0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
  0.0      0.0      0.0      0.0         0.0      0.0      0.0      0.0   
 

In [68]:
model.components[:UrbanDemand].Parameters.domesticdemand

64x12 Array{Float64,2}:
 211.562     194.654     192.382     …   455.107     256.838     226.898   
   7.27263     6.6914      6.6133         15.6447      8.82903     7.79983 
 710.929     654.112     646.477        1529.33      863.074     762.465   
  11.3858     10.4759     10.3536         24.493      13.8225     12.2112  
   1.19223     1.09695     1.08415         2.56471     1.44738     1.27866 
   1.96719     1.80997     1.78884   …     4.23177     2.38818     2.10979 
 200.653     184.617     182.462         431.64      243.594     215.199   
  28.3752     26.1074     25.8027         61.04       34.4477     30.4321  
   7.6303      7.02049     6.93854        16.4141      9.26325     8.18343 
   1.49029     1.37119     1.35518         3.20588     1.80923     1.59833 
   3.81515     3.51024     3.46927   …     8.20706     4.63162     4.09171 
   7.80913     7.18503     7.10116        16.7988      9.48035     8.37523 
   1.84796     1.70027     1.68043         3.9753      2.24344  

In [55]:
function initurbandemandcolorado(m::Model)
    urbandemand = addcomponent(m, Urbandemand)
    recorded = readtable(datapath("Colorado/domestic.csv"));

    urbandemand[:domesticdemand] = convert(Matrix, recorded)/1000.;
    M = zeros(m.indices_counts[:regions], m.indices_counts[:time]);
    urbandemand[:commercialdemand] = 0*M;
    urbandemand
end


initurbandemandcolorado (generic function with 1 method)

In [56]:
function initagriculturecolorado(m::Model)
    agriculture = addcomponent(m, Agriculture)
    recorded = readtable(datapath("Colorado/agriculture.csv"));
    agriculture[:water_demand] = convert(Matrix, recorded)/1000.;

    agriculture
end


initagriculturecolorado (generic function with 1 method)